"""empty message

Revision ID: 71732d98b281
Revises: 
Create Date: 2023-10-24 14:52:57.216307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71732d98b281'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.Column('max_temp', sa.Integer(), nullable=True),
    sa.Column('mid_temp', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clothes_table'))
    )
    op.create_table('event_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_table'))
    )
    op.create_table('user_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_table')),
    sa.UniqueConstraint('email', name=op.f('uq_user_table_email'))
    )
    op.create_table('closet_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes_table.id'], name=op.f('fk_closet_table_clothes_id_clothes_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_closet_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_closet_table'))
    )
    op.create_table('history_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('clothes_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clothes_id'], ['clothes_table.id'], name=op.f('fk_history_table_clothes_id_clothes_table')),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], name=op.f('fk_history_table_event_id_event_table')),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], name=op.f('fk_history_table_user_id_user_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_history_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_table')
    op.drop_table('closet_table')
    op.drop_table('user_table')
    op.drop_table('event_table')
    op.drop_table('clothes_table')
    # ### end Alembic commands ###
